name = "SPGLM"
uuid = "3b216ecb-567d-4574-94db-2478f4161e1c"
authors = ["thomas.zhihao.luo <thomas.zhihao.luo@gmail.com>"]
version = "0.1.0"

[deps]
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
